#1.)

Create a vector (array) of 1XN dimension representing N-
dimensional feature vector of a sample. Write a program to

compute the mean and variance of the elements present in the
array.

In [8]:
import numpy as np
N = 10
x = np.array([2,4,8,3,10,5,7,5,9,1]) #sample vector
print("Sample Vector (1 x 10) :",x)

Mean = np.mean(x)
Variance = np.var(x)

print("Mean :",Mean)
print("Variance :",Variance)




Sample Vector (1 x 10) : [ 2  4  8  3 10  5  7  5  9  1]
Mean : 5.4
Variance : 8.239999999999998


##Sample Variance

In [14]:
m=np.mean(x)
s=0
for i in range(N):
  s = s + (x[i]-m)**2
sv = s/(N-1)
print("Sample Variance :",sv)

Sample Variance : 9.155555555555557


##Population Variance

In [11]:
pv  = np.var(x)
print("Population Variance :",pv)

Population Variance : 8.239999999999998


Mean : It is the average of the sample.Represents the central value of the data by which it is distributed .Calculated as the sum of all data points divided by the number of points.

Variance :  Variance is the measure of how the sample data is spreaded around the mean. It quantifies the degree of dispersion or variability in a dataset.

#2.)

Create two vectors each of dimension 1XM each representing N-
dimensional feature vector of a sample. Write a program to

compute the Covariance between them.

In [17]:
X = np.array([2,7,1,5,14,8,3,10,12,17])
Y = np.array([11,3,6,9,10,15,6,3,4,1])
print("X (1 x 10):",X)
print("Y (1 x 10):",Y)

X (1 x 10): [ 2  7  1  5 14  8  3 10 12 17]
Y (1 x 10): [11  3  6  9 10 15  6  3  4  1]


##CoVariance

In [18]:
mean_X = np.mean(X)
mean_Y = np.mean(Y)
cov_xy = np.mean((X-mean_X)*(Y-mean_Y))
print("CoVariance :",cov_xy)

CoVariance : -7.019999999999999


CoVariance : Covariance between two vectors represents the extent to which two variables change together. If the covariance is positive, it means that as one vector increases, the other tends to increase as well. If the covariance is negative, as one vector increases, the other tends to decrease. A covariance of zero suggests there is no linear relationship between the two vectors.

#3.)
Create two vectors each of dimension 1XN. Write a program to
compute the Correlation between them.

In [20]:
X = np.array([2,7,1,5,14,8,3,10,12,17])
Y = np.array([11,3,6,9,10,15,6,3,4,1])
print("X (1 x 10):",X)
print("Y (1 x 10):",Y)

X (1 x 10): [ 2  7  1  5 14  8  3 10 12 17]
Y (1 x 10): [11  3  6  9 10 15  6  3  4  1]


##Correlation

In [21]:
mean_X = np.mean(X)
mean_Y = np.mean(Y)
std_X = np.std(X)
std_Y = np.std(Y)
cov_xy = np.mean((X-mean_X)*(Y-mean_Y))
corr_xy = cov_xy/(std_X*std_Y)
print("Correlation :",corr_xy)

Correlation : -0.33434622050524465


-> Correlation : Correlation represents the strength and direction of the linear relationship between two variables or vectors. It is a normalized version of covariance, providing a measure that ranges from -1 to 1:

+1: Perfect positive linear relationship (as one variable increases, the other also increases proportionally).
-1: Perfect negative linear relationship (as one variable increases, the other decreases proportionally).
0: No linear relationship (the variables are independent or have no predictable pattern).

#4.)
Create a Matrix of MXN dimension representing the M-dimensional
feature vector for N number of samples i. e (i,j)th entry of the matrix
represents the ith feature of jth sample. Write a program to compute
the covariance matrix and correlation matrix. Comment on
takeaways from these matrixes.

In [25]:
M = 3
N = 4
matrix = np.array([[2, 7, 1, 5],
                 [14, 8, 3, 10],
                 [12, 17, 6, 3]])
print("Matrix (3 x 4):\n",matrix)
cov = np.cov(matrix)
print("Covariance Matrix:\n",cov)
corr = np.corrcoef(matrix)
print("Correlation Matrix:\n",corr)



Matrix (3 x 4):
 [[ 2  7  1  5]
 [14  8  3 10]
 [12 17  6  3]]
Covariance Matrix:
 [[ 7.58333333  1.91666667  7.16666667]
 [ 1.91666667 20.91666667  6.5       ]
 [ 7.16666667  6.5        39.        ]]
Correlation Matrix:
 [[1.         0.15218445 0.41673006]
 [0.15218445 1.         0.22758038]
 [0.41673006 0.22758038 1.        ]]


CoVariance matrix : The covariance matrix indicates the degree to which features vary together. Positive values indicate that features tend to increase together, while negative values indicate that one feature tends to decrease as the other increases.
-The diagonal values of the covariance matrix represent the variance of each feature.

Correlation matrix : Correlation matrix provides a normalized measure of the relationship between features, ranging from -1 to 1. It gives a clearer picture of linear relationships between features, regardless of their scales.
-High correlation values (close to 1 or -1) between features may indicate redundancy in the dataset, suggesting that feature selection techniques might be beneficial.